### ISSUE TITLE
shouldn't be using $JENKINS_HOME

### ISSUE THREAD

**Issue by BenWildeman** [pedrocesar-ti/Xenv-jenkins-lib#1]
in your script, you use $JENKINS_HOME for installing but this isn't correct. when running this on a slave, the $JENKINS_HOME always points to the master, and thus never exists on the slave where the installation should be ran

**Comment by pedrocesarti** [comment]
I believe that the issue can be closed based on @Gremkow PR. 

Cheers

**Comment by pedrocesarti** [comment]
@BenWildeman you can let me know if you have any other issue using the lib or if you would like to add any feature.
